version: "3.9"
services:
  solarmonitor:
    container_name: "talents-monitoring"
    build: .
    ports:
      - "3000:3000/tcp"
    restart: "unless-stopped"
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      TZ: "Europe/Berlin"
      LOG_LEVEL: "debug"
      API_USERNAME: "*********"
      API_PASSWORD: "*********"
      REST_ENABLED: true
      PROMETHEUS_ENABLED: true
      MQTT_ENABLED: true
      MQTT_HOST: "192.168.x.x"
      MQTT_USERNAME: "*******"
      MQTT_PASSWORD: "*******"
      DEVICE_PANEL_MANUFACTURER: "Risen"
      DEVICE_PANEL_MODEL: "Risen Titan 410 Wp - S RSM40-410M"
